name: Generate ISO9660 template for new BlissOS from Docker Image

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      
      - name: Build initrd template
        run: |
          # Get dependencies
          sudo apt install shfmt make grub-common grub2-common grub-pc-bin grub-efi-ia32-bin grub-efi-amd64-bin xorriso mtools

          # Build initrd src
          cd initrd
          mkdir out
          make DESTDIR=out

          # Clean up
          sudo rm -rf src .gitignore Makefile README.md

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile . -t devuan

      - name: Extract RootFS & generate grub-rescue.iso
        run: |
          # Create Docker image
          docker create --name devuan devuan echo "Devuan"

          # Export it to install
          mkdir install
          docker export devuan | tar -C install -p -s -xv

          # Move iso out
          mv install/iso .

          # Remove .dockerenv
          rm -rf install/.dockerenv

          # Change ownership of install/ to 0:0
          sudo chown -R 0:0 install

          # Change chmod of dbus-daemon-launch-helper to 4754 with ownership 0:101
          sudo chown 0:101 install/usr/lib/dbus-1.0/dbus-daemon-launch-helper
          sudo chmod 4754 install/usr/lib/dbus-1.0/dbus-daemon-launch-helper

          # Create install.sfs
          sudo mksquashfs install iso/install.sfs -noappend -comp zstd

          # Create template iso
          sudo grub-mkrescue -o grub-rescue.iso --modules="part_msdos part_gpt part_apple fat exfat ext2 btrfs hfs ntfs" iso

          # Clean up
          sudo rm -rf install iso
          docker rm devuan

      - name: Set Vars
        id: vars
        run: |
          echo "arch=$(dpkg --print-architecture)" >> "$GITHUB_OUTPUT"

      - name: Upload grub-rescue.iso
        uses: actions/upload-artifact@v4
        with:
          name: grub-rescue.iso
          path: grub-rescue.iso

  release:
    name: Release
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download RootFS
        id: download-rootfs
        uses: actions/download-artifact@v4
        with:
          path: out
          pattern: 'install.sfs,initrd_lib.tar.gz,grub-rescue.iso,boot_hybrid.img'
          merge-multiple: true

      - name: List Files
        run: ls -R ${{ steps.download-rootfs.outputs.download-path }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          prerelease: false
          files: |
            ${{ steps.download-rootfs.outputs.download-path }}/*.tar.gz
